### ISSUE TITLE
Assertion error on teleport

### ISSUE THREAD

**Issue by emerald000** [ejedev/chompy-hunter#1]
I was killing Hellhounds in Witchhaven. I downloaded and activated the plugin while doing so. I teleported to Varrock using the normal spellbook. I got an error:

```
[Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.AssertionError: null
	at ejedev.chompyhunter.ChompyHunterPlugin.onNpcSpawned(ChompyHunterPlugin.java:94)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:69)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:183)
	at client.my(client.java:21613)
	at client.ao(client.java)
	at br.ab(br.java:362)
	at br.run(br.java:316)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ejedev** [comment]
Thank you for bringing this to my attention. I'm fairly new at writing plugins so I will do my best to test and resolve this. Seems I forgot error handling for the NPC Spawn event although I'm not sure what caused it.

**Comment by ejedev** [comment]
The issue is that I was asserting a name was not null without a proper check. I'll be testing a fix later today.
